PL-26 - Write Encoder
ConsiderItDone/polywrap-go pull request #2
Opened 2022-06-18 14:28 UTC by ramilexe

2022-06-30 12:48 UTC, fetsorn commented on polywrap/msgpack/write_encoder_test.go
> +		{name: "zero", input: 0, want: []byte{208, 0}},
should this be []bytes{0}?

2022-06-30 12:55 UTC, fetsorn requested changes
int8 zero should be a single zero byte. 
Also we might want to call the functions WriteInt8 instead of WriteI8, to keep the assemblyscript naming convention. Wasm/rs uses "write_i8" but Rust has "i8" instead of "int8" so it makes more sense there.

P.S. Thanks for awesome work on test cases, a port of this to wasm/as has been merged and wasm/rs is under way.

2022-06-30 12:55 UTC, fetsorn commented on polywrap/msgpack/write_encoder_test.go
> +		{name: "zero", input: 0, want: []byte{208, 0}},
Should zero be []bytes{0}?

2022-07-05 15:41 UTC, ramilexe commented on polywrap/msgpack/write_encoder_test.go
> +		{name: "zero", input: 0, want: []byte{208, 0}},
@fetsorn thank you for your report, it is fixed in https://github.com/ConsiderItDone/polywrap-go/pull/2/commits/c3b2aa211a6ac12a5b45b1001b643b37cb64e160

2022-07-05 15:42 UTC, merged